services:
  postgres_master:
    image: postgres:16.3
    container_name: postgres_primary
    hostname: "primary.postgresql.todo"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "userRaj"
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "todoDB"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5455:5432
